// Every sound, including the score, is synthesized locally. No audio files.
export class Soundtrack{
 ctx:AudioContext|null=null; master:GainNode|null=null; noise:GainNode|null=null; filter:BiquadFilterNode|null=null; muted=false; next=0; beat=0; running=false;
 start(){if(!this.ctx){this.ctx=new AudioContext();const c=this.ctx;this.master=c.createGain();this.master.gain.value=this.muted?0:.25;this.master.connect(c.destination);const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),d=buffer.getChannelData(0);let seed=294;for(let i=0;i<d.length;i++){seed=(seed*16807)%2147483647;d[i]=seed/1073741824-1;}const src=c.createBufferSource();src.buffer=buffer;src.loop=true;this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=400;this.noise=c.createGain();this.noise.gain.value=0;src.connect(this.filter);this.filter.connect(this.noise);this.noise.connect(this.master);src.start();this.next=c.currentTime;}
 this.ctx.resume().catch(()=>{});this.running=true;}
 tone(freq:number,time:number,duration:number,volume:number,type:OscillatorType='triangle',end?:number){const c=this.ctx;if(!c||!this.master)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);if(end)o.frequency.exponentialRampToValueAtTime(end,time+duration);g.gain.setValueAtTime(volume,time);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g);g.connect(this.master);o.start(time);o.stop(time+duration+.03);o.onended=()=>{o.disconnect();g.disconnect()};}
 update(speed:number,rain:number,slip:number,boost:boolean){const c=this.ctx;if(!c||!this.running)return;this.noise!.gain.setTargetAtTime(.025+speed/200+rain*.13+slip*.12,c.currentTime,.15);this.filter!.frequency.setTargetAtTime(250+speed*44+slip*1000,c.currentTime,.2);while(this.next<c.currentTime+.12){const t=Math.max(this.next,c.currentTime),n=this.beat%32;const bass=[55,55,65.406,48.999][Math.floor(n/8)];if(n%4===0)this.tone(130,t,.23,.8,'sine',38);if(n%8===4)this.tone(220,t,.08,.09,'triangle',100);if(n%2===0)this.tone(bass,t,.45,.13,'sine');const notes=[293.66,329.63,392,440,493.88,440,392,329.63];if(n%2===1||boost){const f=notes[(n*3)%8];this.tone(f,t,.48,.13,'triangle');this.tone(f*2,t,.16,.035,'sine');this.tone(f,t+.19,.4,.024,'sine');}this.next+=60/(boost?130:106)/4;this.beat++;}}
 hit(){if(this.ctx)this.tone(80,this.ctx.currentTime,.28,.8,'sawtooth',22)}
 land(){if(this.ctx)this.tone(100,this.ctx.currentTime,.15,.3,'triangle',35)}
 mute(value:boolean){this.muted=value;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(value?0:.25,this.ctx.currentTime,.04)}
 pause(value:boolean){this.running=!value;if(value)this.ctx?.suspend().catch(()=>{});else if(this.ctx){this.next=this.ctx.currentTime;this.ctx.resume().catch(()=>{})}}
 dispose(){this.ctx?.close().catch(()=>{})}
}
